config:
  type: http
validatingWebhookConfiguration:
  certificates:
    certManager:
      issuerRef:
        group: cert-manager.io
        kind: ClusterIssuer
        name: selfsigned-issuer
  http:
      # controls the http address
      nestedRequest: true
      address: :9081